AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  lambda4cicd:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: 'Lambda_CICD function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::342259560604:role/MyLambdaRole'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment: 
        Variables:
            REGION: us-east-1